Machane!!

ithu y = 20 aanu
para ( y ) ;
ithu z = x > y aanu
para ( z ) ;
ithu obj = { x : 100 , y : 200 , } aanu

para ( obj . x  + obj . y ) ;
para ( "Hello World!!" ) ;

veluthu ( x , y ) ;
cheruthu ( x , y ) ;

ithu arr = [ 1 , 2 ] aanu

para ( arr [ 0 ] + arr [ 1 ] ) ;

para ( arr ) ;

ithu const w = 20 aanu

para ( w ) ;

w = w + 1 

ithu q = 100 aanu

ipo ( obj . x != obj . y ) anengi { q = q + 50 } alengi { q = q + 100 } 

para ( q ) ;